In [167]:
import pandas as pd
import numpy as np

In [168]:
df = pd.read_excel("../TFM/Wyscout/jugadoresLimpioConPosiciones.xlsx")

In [169]:
df.head()

,Jugador,Equipo,Posicion,Edad,VM,FinContrato,Nacionalidad,Pie,Cedido,PartidosJugados,...,GolesEvitados,GolesEvitados/90,Salidas/90,DuelosAereosPortero90,TirosLibres/90,TirosLibresDirecto/90,%TirosLibresDirecto,Córneres/90,Penaltis,%PenaltisConvertidos
0,J. Mvondo,Albacete,ED,22.0,800000,2021-06-30,Cameroon,derecho,no,10,...,0.00,0.000,0.0,0.00,0.00,0.00,0.0,0.00,0,0.0
1,Tomeu Nadal,Albacete,POR,31.0,800000,2021-06-30,Spain,derecho,no,20,...,2.32,0.109,0.8,0.19,0.00,0.00,0.0,0.00,0,0.0
2,Fran García,Albacete,LI,28.0,600000,2021-06-30,Spain,izquierdo,no,8,...,0.00,0.000,0.0,0.00,0.35,0.00,0.0,0.53,0,0.0
3,Diego Caballo,Albacete,LI,26.0,600000,2022-06-30,Spain,izquierdo,no,15,...,0.00,0.000,0.0,0.00,1.27,0.27,25.0,0.73,0,0.0
4,Eddy Silvestre,Albacete,MC,28.0,600000,2023-06-30,Spain,derecho,no,16,...,0.00,0.000,0.0,0.00,0.00,0.00,0.0,0.00,0,0.0

In [170]:
#Filtramos por posicion
df = df[(df.Posicion == "POR") & (df.MinutosJugados >= 900)]

In [171]:
df.shape

(21, 108)

In [172]:
#Primer dataframe con las columnas que vamos a utilizar
subdf = pd.DataFrame(df,columns=['Jugador','Equipo','Edad','VM','MinutosJugados','GolesRecibidos','GolesRecibidos/90'
    ,'RematesContra','RematesContra/90','PorteriasImbatidas','%Paradas','xGEnContra','xGEnContra/90'
    ,'GolesEvitados','GolesEvitados/90','Salidas/90','%DuelosAereosGanados','%PrecisionPasesLargos']) #Varias columnas

In [173]:
subdf.head()

,Jugador,Equipo,Edad,VM,MinutosJugados,GolesRecibidos,GolesRecibidos/90,RematesContra,RematesContra/90,PorteriasImbatidas,%Paradas,xGEnContra,xGEnContra/90,GolesEvitados,GolesEvitados/90,Salidas/90,%DuelosAereosGanados,%PrecisionPasesLargos
1,Tomeu Nadal,Albacete,31.0,800000,1914,26,1.22,83,3.90,5,68.67,28.32,1.33,2.32,0.109,0.80,100.00,82.10
39,Dani Jiménez,Alcorcón,30.0,300000,1907,18,0.85,61,2.88,7,70.49,18.14,0.86,0.14,0.007,1.04,87.50,76.90
68,G. Makaridze,Almería,30.0,1200000,1176,8,0.61,32,2.45,5,75.00,8.42,0.64,0.42,0.032,2.60,85.71,67.24
118,Marc Martínez,Cartagena,30.0,300000,1642,23,1.26,65,3.56,3,64.62,19.75,1.08,-3.25,-0.178,1.75,77.78,72.89
151,Álvaro Campos,Castellón,33.0,200000,1215,16,1.19,39,2.89,2,58.97,14.25,1.06,-1.75,-0.130,0.52,100.00,75.00

In [174]:
#Creacion de columnas nuevas que queramos calcular a partir de otras
subdf['xG/RemateContra'] = subdf.apply(lambda row: row['xGEnContra']/row['RematesContra'], axis=1).round(2)
subdf.head()

,Jugador,Equipo,Edad,VM,MinutosJugados,GolesRecibidos,GolesRecibidos/90,RematesContra,RematesContra/90,PorteriasImbatidas,%Paradas,xGEnContra,xGEnContra/90,GolesEvitados,GolesEvitados/90,Salidas/90,%DuelosAereosGanados,%PrecisionPasesLargos,xG/RemateContra
1,Tomeu Nadal,Albacete,31.0,800000,1914,26,1.22,83,3.90,5,68.67,28.32,1.33,2.32,0.109,0.80,100.00,82.10,0.34
39,Dani Jiménez,Alcorcón,30.0,300000,1907,18,0.85,61,2.88,7,70.49,18.14,0.86,0.14,0.007,1.04,87.50,76.90,0.30
68,G. Makaridze,Almería,30.0,1200000,1176,8,0.61,32,2.45,5,75.00,8.42,0.64,0.42,0.032,2.60,85.71,67.24,0.26
118,Marc Martínez,Cartagena,30.0,300000,1642,23,1.26,65,3.56,3,64.62,19.75,1.08,-3.25,-0.178,1.75,77.78,72.89,0.30
151,Álvaro Campos,Castellón,33.0,200000,1215,16,1.19,39,2.89,2,58.97,14.25,1.06,-1.75,-0.130,0.52,100.00,75.00,0.37

In [175]:
subdf.describe()

,Edad,VM,MinutosJugados,GolesRecibidos,GolesRecibidos/90,RematesContra,RematesContra/90,PorteriasImbatidas,%Paradas,xGEnContra,xGEnContra/90,GolesEvitados,GolesEvitados/90,Salidas/90,%DuelosAereosGanados,%PrecisionPasesLargos,xG/RemateContra
count,21.000000,2.100000e+01,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000
mean,30.380952,5.000000e+05,1603.666667,15.666667,0.889524,55.142857,3.063810,6.380952,71.146667,15.728095,0.885714,0.061429,-0.003857,1.269048,91.367619,70.583333,0.288095
std,4.177035,3.316625e+05,315.321000,5.461990,0.279723,17.185126,0.611281,3.057388,6.527732,5.056300,0.225490,2.185825,0.121539,0.521084,12.743143,7.332087,0.042381
min,23.000000,2.000000e+05,960.000000,8.000000,0.420000,26.000000,1.970000,2.000000,58.970000,8.300000,0.510000,-3.250000,-0.198000,0.520000,50.000000,57.640000,0.220000
25%,27.000000,3.000000e+05,1351.000000,12.000000,0.680000,40.000000,2.660000,4.000000,65.220000,11.710000,0.660000,-1.580000,-0.113000,0.890000,85.710000,66.230000,0.260000
50%,30.000000,4.000000e+05,1728.000000,16.000000,0.850000,56.000000,3.120000,6.000000,70.490000,15.950000,0.920000,0.140000,0.007000,1.280000,100.000000,71.640000,0.290000
75%,33.000000,5.000000e+05,1896.000000,19.000000,1.130000,68.000000,3.510000,8.000000,75.000000,18.310000,1.060000,1.630000,0.085000,1.580000,100.000000,75.170000,0.310000
max,39.000000,1.500000e+06,1931.000000,26.000000,1.320000,89.000000,4.380000,14.000000,82.140000,28.320000,1.330000,5.310000,0.277000,2.600000,100.000000,82.100000,0.370000

In [176]:
subdf.columns

Index(['Jugador', 'Equipo', 'Edad', 'VM', 'MinutosJugados', 'GolesRecibidos',
       'GolesRecibidos/90', 'RematesContra', 'RematesContra/90',
       'PorteriasImbatidas', '%Paradas', 'xGEnContra', 'xGEnContra/90',
       'GolesEvitados', 'GolesEvitados/90', 'Salidas/90',
       '%DuelosAereosGanados', '%PrecisionPasesLargos', 'xG/RemateContra'],
      dtype='object')

In [177]:
#Columnas que vamos a ponderar
subdf2 = pd.DataFrame(subdf,columns=['Jugador','%Paradas','GolesEvitados'
                            ,'%DuelosAereosGanados','%PrecisionPasesLargos','xG/RemateContra']) #Varias columnas
subdf2.head()

,Jugador,%Paradas,GolesEvitados,%DuelosAereosGanados,%PrecisionPasesLargos,xG/RemateContra
1,Tomeu Nadal,68.67,2.32,100.00,82.10,0.34
39,Dani Jiménez,70.49,0.14,87.50,76.90,0.30
68,G. Makaridze,75.00,0.42,85.71,67.24,0.26
118,Marc Martínez,64.62,-3.25,77.78,72.89,0.30
151,Álvaro Campos,58.97,-1.75,100.00,75.00,0.37

In [178]:
#Normalizamos cada columna por el mayor y damos el valor de la ponderizacion
subdf2['%Paradas'] = ((subdf2['%Paradas']/subdf2['%Paradas'].max())*1.2).round(2)
subdf2['GolesEvitados'] = ((subdf2['GolesEvitados']/subdf2['GolesEvitados'].max())*3).round(2)
subdf2['%DuelosAereosGanados'] = ((subdf2['%DuelosAereosGanados']/subdf2['%DuelosAereosGanados'].max())*1.4).round(2)
subdf2['%PrecisionPasesLargos'] = ((subdf2['%PrecisionPasesLargos']/subdf2['%PrecisionPasesLargos'].max())*1.4).round(2)
subdf2['xG/RemateContra'] = ((subdf2['xG/RemateContra']/subdf2['xG/RemateContra'].max())*2).round(2)
subdf2.head()

,Jugador,%Paradas,GolesEvitados,%DuelosAereosGanados,%PrecisionPasesLargos,xG/RemateContra
1,Tomeu Nadal,1.00,1.31,1.40,1.40,1.84
39,Dani Jiménez,1.03,0.08,1.22,1.31,1.62
68,G. Makaridze,1.10,0.24,1.20,1.15,1.41
118,Marc Martínez,0.94,-1.84,1.09,1.24,1.62
151,Álvaro Campos,0.86,-0.99,1.40,1.28,2.00

In [179]:
subdf2['PuntuacionTotal']= subdf2.iloc[:, -5:-1].sum(axis=1)
subdf2 = subdf2.sort_values(by='PuntuacionTotal', ascending=False)
subdf2.head()

,Jugador,%Paradas,GolesEvitados,%DuelosAereosGanados,%PrecisionPasesLargos,xG/RemateContra,PuntuacionTotal
238,Juan Carlos,1.18,3.00,1.4,1.22,1.46,6.80
183,Diego López,1.20,1.92,1.4,1.08,1.30,5.60
1,Tomeu Nadal,1.00,1.31,1.4,1.40,1.84,5.11
383,Manolo Reina,1.20,1.08,1.4,1.17,1.19,4.85
489,Joan Femenías,1.07,0.92,1.4,1.24,1.57,4.63

In [180]:
dfSinColumnas = df.drop(['%Paradas','GolesEvitados'
                            ,'%DuelosAereosGanados','%PrecisionPasesLargos'], axis=1)
dfSinColumnas.head()

,Jugador,Equipo,Posicion,Edad,VM,FinContrato,Nacionalidad,Pie,Cedido,PartidosJugados,...,xGEnContra/90,GolesEvitados/90,Salidas/90,DuelosAereosPortero90,TirosLibres/90,TirosLibresDirecto/90,%TirosLibresDirecto,Córneres/90,Penaltis,%PenaltisConvertidos
1,Tomeu Nadal,Albacete,POR,31.0,800000,2021-06-30,Spain,derecho,no,20,...,1.33,0.109,0.80,0.19,0.0,0.0,0.0,0.0,0,0.0
39,Dani Jiménez,Alcorcón,POR,30.0,300000,2022-06-30,Spain,derecho,no,20,...,0.86,0.007,1.04,0.38,0.0,0.0,0.0,0.0,0,0.0
68,G. Makaridze,Almería,POR,30.0,1200000,2022-06-30,Georgia,derecho,no,13,...,0.64,0.032,2.60,0.54,0.0,0.0,0.0,0.0,0,0.0
118,Marc Martínez,Cartagena,POR,30.0,300000,2021-06-30,Spain,derecho,no,17,...,1.08,-0.178,1.75,0.49,0.0,0.0,0.0,0.0,0,0.0
151,Álvaro Campos,Castellón,POR,33.0,200000,2022-06-30,Spain,izquierdo,no,13,...,1.06,-0.130,0.52,0.22,0.0,0.0,0.0,0.0,0,0.0

In [181]:
#Creamos dataframe con aspectos basicos del jugador para añadir al dataframe final
dfFinal = pd.merge(subdf2,dfSinColumnas, on='Jugador', how='left')
dfFinal.head()

,Jugador,%Paradas,GolesEvitados,%DuelosAereosGanados,%PrecisionPasesLargos,xG/RemateContra,PuntuacionTotal,Equipo,Posicion,Edad,...,xGEnContra/90,GolesEvitados/90,Salidas/90,DuelosAereosPortero90,TirosLibres/90,TirosLibresDirecto/90,%TirosLibresDirecto,Córneres/90,Penaltis,%PenaltisConvertidos
0,Juan Carlos,1.18,3.00,1.4,1.22,1.46,6.80,Girona,POR,32.0,...,0.95,0.277,0.99,0.16,0.0,0.0,0.0,0.0,0,0.0
1,Diego López,1.20,1.92,1.4,1.08,1.30,5.60,Espanyol,POR,39.0,...,0.64,0.161,1.28,0.33,0.0,0.0,0.0,0.0,0,0.0
2,Tomeu Nadal,1.00,1.31,1.4,1.40,1.84,5.11,Albacete,POR,31.0,...,1.33,0.109,0.80,0.19,0.0,0.0,0.0,0.0,0,0.0
3,Manolo Reina,1.20,1.08,1.4,1.17,1.19,4.85,Mallorca,POR,35.0,...,0.51,0.090,1.46,0.28,0.0,0.0,0.0,0.0,0,0.0
4,Joan Femenías,1.07,0.92,1.4,1.24,1.57,4.63,Real Oviedo,POR,24.0,...,0.92,0.085,0.68,0.05,0.0,0.0,0.0,0.0,0,0.0

In [184]:
dfFinal.to_csv("puntuacionPorteros.csv", encoding="utf-8-sig")